package Project;

import java.sql.*;
import java.io.File;
import javax.swing.JOptionPane;

public class AddTask extends javax.swing.JFrame {

    Database db = new Database();
    public final String url = "jdbc:sqlite:tasksDB";

    /**
     * Creates new form AddTask
     */
    public AddTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lpBackground = new javax.swing.JLayeredPane();
        lblDescription = new javax.swing.JLabel();
        lblOptionalCategory = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDescription = new javax.swing.JTextArea();
        btnAddCategory = new javax.swing.JButton();
        lblCompletionStatus = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        cmbCompletionStatus = new javax.swing.JComboBox<>();
        btnAddTask = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        txtOptionalCategory = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 51, 51));
        lblTitle.setText("Add Task");

        lpBackground.setBackground(new java.awt.Color(204, 204, 204));
        lpBackground.setOpaque(true);

        lblDescription.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(51, 51, 51));
        lblDescription.setText("Description:");

        lblOptionalCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOptionalCategory.setForeground(new java.awt.Color(51, 51, 51));
        lblOptionalCategory.setText("Add Category - Optional");

        txtareaDescription.setColumns(20);
        txtareaDescription.setLineWrap(true);
        txtareaDescription.setRows(5);
        jScrollPane1.setViewportView(txtareaDescription);

        btnAddCategory.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAddCategory.setForeground(new java.awt.Color(51, 51, 51));
        btnAddCategory.setText("Add");
        btnAddCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        lblCompletionStatus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCompletionStatus.setForeground(new java.awt.Color(51, 51, 51));
        lblCompletionStatus.setText("Completion Status:");

        lblCategory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(51, 51, 51));
        lblCategory.setText("Category:");

        cmbCompletionStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Completed", "Not Completed" }));
        cmbCompletionStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnAddTask.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAddTask.setForeground(new java.awt.Color(51, 51, 51));
        btnAddTask.setText("Add Task");
        btnAddTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(51, 51, 51));
        lblName.setText("Name:");

        cmbCategory.setToolTipText("");
        cmbCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lpBackground.setLayer(lblDescription, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblOptionalCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnAddCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblCompletionStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(cmbCompletionStatus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnAddTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(cmbCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(txtName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(txtOptionalCategory, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpBackgroundLayout = new javax.swing.GroupLayout(lpBackground);
        lpBackground.setLayout(lpBackgroundLayout);
        lpBackgroundLayout.setHorizontalGroup(
            lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lpBackgroundLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddTask))
                    .addGroup(lpBackgroundLayout.createSequentialGroup()
                        .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblCompletionStatus)
                            .addComponent(lblDescription)
                            .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmbCategory, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbCompletionStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCategory)
                            .addGroup(lpBackgroundLayout.createSequentialGroup()
                                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtOptionalCategory)
                                    .addComponent(lblOptionalCategory))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        lpBackgroundLayout.setVerticalGroup(
            lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCompletionStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCompletionStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOptionalCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOptionalCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddCategory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTask)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lpBackground)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lpBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // Clears all input fields in the form
    public void clearALl() {
        txtName.setText("");
        txtareaDescription.setText("");
        cmbCompletionStatus.setSelectedIndex(0);
        cmbCategory.setSelectedIndex(0);
    }

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        File f = new File("tasksDB");

        if (f.exists()) {
            try {
                Connection connection = DriverManager.getConnection(url);
                String sql = "INSERT INTO TasksTbl (Name, Description, Completion_Status, Category)"
                        + "VALUES ('" + txtName.getText()
                        + "', '" + txtareaDescription.getText()
                        + "', '" + cmbCompletionStatus.getSelectedItem().toString()
                        + "', '" + cmbCategory.getSelectedItem().toString() + "')";

                Statement statement = connection.createStatement();

                statement.execute(sql);

                JOptionPane.showMessageDialog(rootPane, "Data succesfully added");

                statement.close();
                connection.close();

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
            }
        }

        clearALl();
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        File f = new File("tasksDB");
        String newCategory = txtOptionalCategory.getText().trim();

        if (!newCategory.isEmpty()) {
            if (f.exists()) {
                try {
                    Connection connection = DriverManager.getConnection(url);
                    String sql = "INSERT INTO CategoryTbl ( Category)"
                            + "VALUES ('" + newCategory + "')";

                    Statement statement = connection.createStatement();

                    statement.execute(sql);

                    JOptionPane.showMessageDialog(rootPane, "Category succesfully added");

                    statement.close();
                    connection.close();

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(rootPane, e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please enter a category.");
        }
        cmbCategory.removeAllItems();
        txtOptionalCategory.setText("");
        db.loadCategory(cmbCategory);
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        db.loadCategory(cmbCategory);
    }//GEN-LAST:event_formWindowOpened

    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbCompletionStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblCompletionStatus;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOptionalCategory;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLayeredPane lpBackground;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOptionalCategory;
    private javax.swing.JTextArea txtareaDescription;
    // End of variables declaration//GEN-END:variables
}
