package Project;

import javax.swing.JOptionPane;

public class MenuFrame extends javax.swing.JFrame {

    Database db = new Database();

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        lpBackground = new javax.swing.JLayeredPane();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblFilter = new javax.swing.JLabel();
        cmbFilter = new javax.swing.JComboBox<>();
        lblSortBy = new javax.swing.JLabel();
        radAsc = new javax.swing.JRadioButton();
        radDesc = new javax.swing.JRadioButton();
        btnInsert = new javax.swing.JButton();
        lblInsertTask = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblUpdateTask = new javax.swing.JLabel();
        lblRemoveTask = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        btnSave = new javax.swing.JButton();
        lblSaveTask = new javax.swing.JLabel();
        lblExportTasks = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        cmbSelectTask = new javax.swing.JComboBox<>();
        lblSelectTask = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        cmbRemoveID = new javax.swing.JComboBox<>();
        lblSelectTask1 = new javax.swing.JLabel();
        lblFileType = new javax.swing.JLabel();
        cmbFileType = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTasks = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe Script", 0, 36)); // NOI18N
        lblTitle.setText("Task Manager Application");

        lpBackground.setBackground(new java.awt.Color(204, 204, 204));
        lpBackground.setOpaque(true);

        lblSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(51, 51, 51));
        lblSearch.setText("Search:");

        lblFilter.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblFilter.setForeground(new java.awt.Color(51, 51, 51));
        lblFilter.setText("Filter:");

        cmbFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "ID", "Name", "Description", "Completion_Status", "Category" }));
        cmbFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSortBy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSortBy.setForeground(new java.awt.Color(51, 51, 51));
        lblSortBy.setText("Sort By:");

        buttonGroup1.add(radAsc);
        radAsc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radAsc.setForeground(new java.awt.Color(51, 51, 51));
        radAsc.setText("Ascending");
        radAsc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radAsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAscActionPerformed(evt);
            }
        });

        buttonGroup1.add(radDesc);
        radDesc.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        radDesc.setForeground(new java.awt.Color(51, 51, 51));
        radDesc.setText("Descending");
        radDesc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        radDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDescActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(51, 51, 51));
        btnInsert.setText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        lblInsertTask.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblInsertTask.setForeground(new java.awt.Color(51, 51, 51));
        lblInsertTask.setText("Insert task:");

        btnUpdate.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(51, 51, 51));
        btnUpdate.setText("Update");
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblUpdateTask.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblUpdateTask.setForeground(new java.awt.Color(51, 51, 51));
        lblUpdateTask.setText("Update task:");

        lblRemoveTask.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblRemoveTask.setForeground(new java.awt.Color(51, 51, 51));
        lblRemoveTask.setText("Remove task:");

        btnRemove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(51, 51, 51));
        btnRemove.setText("Remove");
        btnRemove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(51, 51, 51));
        btnSave.setText("Save");
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblSaveTask.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblSaveTask.setForeground(new java.awt.Color(51, 51, 51));
        lblSaveTask.setText("Save Task:");

        lblExportTasks.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblExportTasks.setForeground(new java.awt.Color(51, 51, 51));
        lblExportTasks.setText("Export Tasks:");

        btnExport.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(51, 51, 51));
        btnExport.setText("Export");
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        cmbSelectTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSelectTask.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSelectTask.setForeground(new java.awt.Color(51, 51, 51));
        lblSelectTask.setText("Select Task  ID");

        btnSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search_icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblSelectTask1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSelectTask1.setForeground(new java.awt.Color(51, 51, 51));
        lblSelectTask1.setText("Select Task ID");

        lblFileType.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFileType.setForeground(new java.awt.Color(51, 51, 51));
        lblFileType.setText("Select File Type:");

        cmbFileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Text file", "CSV file" }));

        lpBackground.setLayer(lblSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(txtSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(cmbFilter, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblSortBy, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(radAsc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(radDesc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnInsert, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblInsertTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnUpdate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblUpdateTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblRemoveTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnRemove, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnSave, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblSaveTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblExportTasks, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnExport, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(cmbSelectTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblSelectTask, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(btnSearch, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(cmbRemoveID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblSelectTask1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(lblFileType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        lpBackground.setLayer(cmbFileType, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout lpBackgroundLayout = new javax.swing.GroupLayout(lpBackground);
        lpBackground.setLayout(lpBackgroundLayout);
        lpBackgroundLayout.setHorizontalGroup(
            lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch)
                    .addComponent(jSeparator2)
                    .addGroup(lpBackgroundLayout.createSequentialGroup()
                        .addComponent(cmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                        .addComponent(btnSearch))
                    .addGroup(lpBackgroundLayout.createSequentialGroup()
                        .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInsertTask)
                            .addComponent(lblUpdateTask)
                            .addComponent(lblSortBy)
                            .addComponent(lblSearch)
                            .addComponent(lblFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radAsc)
                            .addComponent(radDesc)
                            .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRemoveTask)
                            .addGroup(lpBackgroundLayout.createSequentialGroup()
                                .addComponent(cmbRemoveID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblSelectTask1)
                            .addComponent(lblSelectTask)
                            .addGroup(lpBackgroundLayout.createSequentialGroup()
                                .addComponent(cmbSelectTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSave))
                            .addComponent(lblSaveTask))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblFileType)
                                .addComponent(cmbFileType, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblExportTasks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExport)))
                .addContainerGap())
        );
        lpBackgroundLayout.setVerticalGroup(
            lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lpBackgroundLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbFilter))
                .addGap(14, 14, 14)
                .addComponent(lblSortBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radAsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radDesc)
                .addGap(18, 18, 18)
                .addComponent(lblInsertTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInsert)
                .addGap(18, 18, 18)
                .addComponent(lblUpdateTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(lblRemoveTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSelectTask1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(cmbRemoveID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lpBackgroundLayout.createSequentialGroup()
                        .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSaveTask)
                            .addComponent(lblExportTasks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSelectTask)
                        .addGap(4, 4, 4)
                        .addGroup(lpBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSelectTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave)
                            .addComponent(cmbFileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExport)))
                    .addGroup(lpBackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblFileType)))
                .addGap(53, 53, 53))
        );

        tblTasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Description", "Completion Status", "Category"
            }
        ));
        jScrollPane2.setViewportView(tblTasks);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE))
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lpBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addComponent(lpBackground))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void refreshcmbID() {
        cmbRemoveID.removeAllItems();
        cmbSelectTask.removeAllItems();
        db.loadID(cmbRemoveID);
        db.loadID(cmbSelectTask);
    }

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        AddTask addTaskFrm = new AddTask();
        addTaskFrm.setVisible(true);
    }//GEN-LAST:event_btnInsertActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        db.createDB();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        db.loadAll(tblTasks);
        refreshcmbID();
    }//GEN-LAST:event_formWindowActivated

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        UpdateTask updateTaskFrm = new UpdateTask();
        updateTaskFrm.setVisible(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchTerm = txtSearch.getText();
        String selectedColumn = cmbFilter.getSelectedItem().toString();

        if (selectedColumn.equals(" ") || selectedColumn.isEmpty()) {
            selectedColumn = "";
        }

        db.searchTasks(tblTasks, searchTerm, selectedColumn);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void radAscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAscActionPerformed
        db.loadSorted(tblTasks, "Ascending");
    }//GEN-LAST:event_radAscActionPerformed

    private void radDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDescActionPerformed
        db.loadSorted(tblTasks, "Descending");
    }//GEN-LAST:event_radDescActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (cmbRemoveID != null) {
            db.removeTask(cmbRemoveID);
        }
        refreshcmbID();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String selectedTaskId = (String) cmbSelectTask.getSelectedItem();
        if (selectedTaskId != null) {
            String filePath = "task_" + selectedTaskId + ".txt";
            db.saveTaskToFile(selectedTaskId, filePath);
            db.displayFileProperties(filePath);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        if (cmbFileType.getSelectedItem().toString().equals("Text file")) {
            db.exportTasksToTextFile("tasks_exported.txt");
            db.displayFileProperties("tasks_exported.txt");
        } else if (cmbFileType.getSelectedItem().toString().equals("CSV file")) {
            db.exportTasksToCSV("tasks_exported.csv");
            db.displayFileProperties("tasks_exported.csv");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Please, select file type");
        }
    }//GEN-LAST:event_btnExportActionPerformed

    public static void main(String args[]) {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbFileType;
    private javax.swing.JComboBox<String> cmbFilter;
    private javax.swing.JComboBox<String> cmbRemoveID;
    private javax.swing.JComboBox<String> cmbSelectTask;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblExportTasks;
    private javax.swing.JLabel lblFileType;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblInsertTask;
    private javax.swing.JLabel lblRemoveTask;
    private javax.swing.JLabel lblSaveTask;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSelectTask;
    private javax.swing.JLabel lblSelectTask1;
    private javax.swing.JLabel lblSortBy;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdateTask;
    private javax.swing.JLayeredPane lpBackground;
    private javax.swing.JRadioButton radAsc;
    private javax.swing.JRadioButton radDesc;
    private javax.swing.JTable tblTasks;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
